#
#
# Notes removed jekyll-feed plugin in favor of https://jekyllcodex.org/without-plugin/rss-feed/

markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - .sass-cache
  - .jekyll-cache
  - .git

permalink: /news/:slug
title: ink
author: Luís Mendes
email: luis@insertcoin.dev
description: >- # this means to ignore newlines until "baseurl:"
  materialization of random thoughts
baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site, e.g. http://example.com
# used by https://github.com/jekyll/jekyll-sitemap
url: "https://ink.insertcoin.dev"

excerpt_separator: "<!--more-->"
google_analytics: G-S86K5Z69JJ

theme_config:
  twitter_username: lmmendes
  github_username:  lmmendes
  linkedin_username: lmmendes
  base_domain_url: insertcoin.dev
  back_home_text: "&larr;" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
